### ISSUE TITLE
周鄭交質 勘誤

### ISSUE THREAD

**Issue by A6669** [Ancient-China-Books/guwenguanzhi#10]
[https://ancient-china-books.github.io/guwenguanzhi/text/part006.html
王貳於虢 當作 王貳于虢.
「蘋」當作繁體,而不是簡體圖片.
建議使用東里本子作校對 https://www.donglishuzhai.net/books/guwenguanzhi.html
在東里本的基礎上勘誤,你這個本子錯誤不少.

**Comment by douglarek** [comment]
> 「蘋」當作繁體,而不是簡體圖片.

這個不怪原電子版，原電子版就是簡體，我是簡繁工具轉的，這個地方會勘誤。



> 建議使用東里本子作校對 https://www.donglishuzhai.net/books/guwenguanzhi.html

這個本子也有標點的問題，我看過。
