### ISSUE TITLE
鄭伯克段于鄢 誤字

### ISSUE THREAD

**Issue by A6669** [Ancient-China-Books/guwenguanzhi#12]
我只看了一篇四校的文章，錯誤還是有點多。
想間一下，每篇文章，閣下打算校幾遍？

既而大叔命西鄙、北鄙貳於己 -＞ 貳于己；
言這遭才好伐了 -＞ 纔好伐了；
將前日惡己愛段之忿一總髮洩 -＞發洩
子之真愛，可以迴天 -＞ 回天
並及於母-＞并及於母
必至於此 -＞于此

**Comment by A6669** [comment]
上述錯誤東里版都沒有，https://www.donglishuzhai.net/chapter/355.html
建議使用東里版，工作量少些。

**Comment by douglarek** [comment]
@A6669 最新的提交已经基于 东篱书斋 了。其实东篱书斋 也有标点和于的区分错误，欢迎勘误。
