### ISSUE TITLE
可否加上安平秋的校勘记

### ISSUE THREAD

**Issue by A6669** [Ancient-China-Books/guwenguanzhi#14]
新版已经采用了东里版本，但是东里版本还有安平秋的校勘记。
例如梓人传 https://www.donglishuzhai.net/chapter/631.html
但是阁下的版本并没有，https://ancient-china-books.github.io/guwenguanzhi/text/part152.html
可否在正文中用另外的颜色的字体加上安平秋的校勘记？

**Comment by douglarek** [comment]
我知道这一点，答案是不会加，会基于中华书局的版本做，错也罢对也罢，一如原文。
