### ISSUE TITLE
体裁问题

### ISSUE THREAD

**Issue by A6669** [Ancient-China-Books/guwenguanzhi#17]
第一卷到第十卷 存在大量的【 和 】这些全部没有必要应该删除。
第十一和第十二卷存在大量标点位置错误。

**Comment by douglarek** [comment]
@A6669 原東里網站也有排版錯誤，只能見一個修一個了：

![image](https://user-images.githubusercontent.com/1488134/172643674-a76e5d1b-6057-4da3-9264-866d36d533eb.png)

**Comment by A6669** [comment]
> @A6669 原東里網站也有排版錯誤，只能見一個修一個了：
> 
> ![image](https://user-images.githubusercontent.com/1488134/172643674-a76e5d1b-6057-4da3-9264-866d36d533eb.png)
> 
> 已修復：[381bd17](https://github.com/Ancient-China-Books/guwenguanzhi/commit/381bd171590197245d8113758041acbfe1457515) 。

東里版是依據 neo du 版https://neodu.com/%E5%8E%9F%E6%B3%A8%E7%89%88%E3%80%8A%E5%8F%A4%E6%96%87%E8%A7%82%E6%AD%A2%E3%80%8B

neo du 版沒有這個問題 https://neodu.com/%e3%80%8a%e5%96%ae%e5%ad%90%e7%9f%a5%e9%99%b3%e5%bf%85%e4%ba%a1%e3%80%8b%e7%b9%81%e9%ab%94%e5%ad%97%e7%89%88.html

另外標題裡穀梁傳的梁寫錯了.
https://ancient-china-books.github.io/guwenguanzhi/text/part053.html

**Comment by douglarek** [comment]
@all-contributors please add @A6669

**Comment by douglarek** [comment]
@all-contributors please add @A6669 for ideas

**Comment by douglarek** [comment]
@all-contributors please add @douglarek for code and maintenance

**Comment by douglarek** [comment]
> 第一卷到第十卷 存在大量的【 和 】这些全部没有必要应该删除。
> 第十一和第十二卷存在大量标点位置错误。

這兩個應該在最新的提交中已經修復，卷十一宋文的前6篇正文已經粗校。

**Comment by douglarek** [comment]
@all-contributors please remove @douglarek

**Comment by douglarek** [comment]
https://github.com/all-contributors please remove @douglarek for code and maintenance

**Comment by douglarek** [comment]
@all-contributors please remove @douglarek for code and maintenance

**Comment by douglarek** [comment]
@all-contributors please add @douglarek for code and maintenance

**Comment by douglarek** [comment]
@all-contributors please add @douglarek for code and maintenance
