### ISSUE TITLE
部分需要修正的地方

### ISSUE THREAD

**Issue by bgc2017** [Ancient-China-Books/guwenguanzhi#26]
間(去聲)道經其門-》 本集作”間“。类似这种的都不宜改为“閒”。虽然以前的部分字典把”間“当作”閒“的俗字，但现在“閒、閑”是”闲“的繁体，”間“是”间“的繁体。有的网站繁简转换后变成了“闲道经其门”，明显是错的，“闲”没有去声，也没有”闲道“这个词汇，只有”间道“。「閒」为「閑」和「間」的初文，从門月，为「間隔」、「空閒」的会意，后来读jian1/jian4的字义分化为「間」，读xian2的分化为「閑」。

<img width="151" alt="s" src="https://user-images.githubusercontent.com/45348499/173181970-fcb4e9a5-165c-43b7-a074-0144c002c6e7.png">

治園於子城之西南-》 治南園於子城之西南。原本不误。南園，園名，廣陵王治蘇州時所建。

露蠶風蟬-》 露蛬風蟬，寒露中的蟋蟀，秋風中的知了。之前“蛬”作“蛩”，也未尝不可。

甯復知-》 寧復知，见本集。《説文解字羣經正字》：「今經典惟以甯為邑名，無以為願詞者。」又如：吾甯樂之、甯力不勝等等，都宜作“寧”。

郡守渭南南大吉-》 郡守渭南南君大吉。”君“字不应删。渭南，地名。南，姓。大吉，名。不直呼姓名，故中间加一”君“字。见本集。

金缸華燭-》 宜照本集改为“金釭”。

**Comment by douglarek** [comment]
> 见本集。

本集指什么？

**Comment by douglarek** [comment]
理論上本電子書不接 「中華書局1959版」古文觀止之外的原文變更，亦即中華書局如果是錯的，或者其他版本認爲它有錯，那麼也不會修改它的內容，之後如果有經歷會在書尾撰寫一份 「辯異」。
